name: board
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: ghcr.io/ppapigo/board-app:latest #board:latest

    container_name: board-back-end
    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-mysql8}
      DB_PORT: "3306"
      DB_NAME: ${DB_NAME:-board}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_UPLOAD_DIR: ${APP_UPLOAD_DIR:-/app/uploads}
      TZ: Asia/Seoul
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8090:8090"
    volumes:
      - uploads:/app/uploads
    networks:
      - board-net
    healthcheck:
      test: ["CMD", "curl", "-fsS","http://localhost:8090/api/board/all"]
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: board-redis
    command: ["redis-server", "--maxmemory", "64mb", "--maxmemory-policy","noeviction"]
    networks:
      - board-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/ppapigo/board-frontend:latest #board-fe-react
    container_name: board-fe-react
    #board-fe-react 가동 조건
    depends_on:
      app:
        condition: service_healthy
    networks:
      board-net:
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://127.0.0.1/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:433"
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-http://localhost}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - board-net
    restart: unless-stopped


networks:
  board-net:
    external: true


volumes:
  uploads: