server:
  port: 8090

spring:
  application:
    name: board

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email #open id connection

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

jwt:
  secret: c2VjcmV0X2tleV9ieV9zYnNfYWNhZGVteV8yMDI2MDcyMV9ib2FyZF9iYWNrX2VuZF9hcHA=
  access-token-validity-seconds: 3600 # 1Hour
  refresh-token-validity-seconds: 36000 # 10Hour

app:
  refresh-cookie:
    name: refreshToken
    secure: false
    same-site: Strict
    path: /api/auth

  oauth:
    kakao:
      appkey: ${KAKAO_REST_API}  # kakao rest api key
      secret: ${KAKAO_SECRET}  # kakao client secret key
      callback: ${KAKAO_CALLBACK}
      authorize-uri: https://kauth.kakao.com/oauth/authorize  # 동의 및 로그인 화면
      token-uri: https://kauth.kakao.com/oauth/token  # access token
      user-info: https://kapi.kakao.com/v2/user/me    # user info

logging:
  level:
    com.sbs.board: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG




