name: Deploy to Lightsail Board server
on:
  push:
    branches: ["main"]
  workflow_dispatch: #재 배포를 위한 수동 트리거 버튼 추가

#병렬 처리 여부
concurrency:
  group: deploy-lightsail
  cancel-in-progress: true #다른 작업이 들어오면 이 작업을 취소함


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: gradlew 실행권한 부여
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew --no-daemon bootJar -x test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lightsail SSH 접속후 배포
        uses: appleboy/ssh-action@v1.2.0

        env:
          KAKAO_REST_API: ${{ secrets.KAKAO_REST_API }}
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          command_timeout: 30m
          envs: KAKAO_REST_API, KAKAO_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, DB_NAME, DB_USERNAME, DB_PASSWORD
          script: |
            set -e
            [ -d ~/board/.git ] || git clone https://github.com/ppapigo/board.git ~/board
            cd ~/board
            git fetch --all && git reset --hard origin/main
            ./scripts/deploy.sh